disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - opening_brace
  - statement_position
  - todo
  - type_body_length
  - void_return
  - modifier_order
  - multiline_parameters
  - multiline_arguments
  - type_name
  - literal_expression_end_indentation
  - for_where
  - closure_end_indentation
  - vertical_parameter_alignment_on_call
  - reduce_boolean
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - for_where
  - implicit_return
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - sorted_first_last
  - vertical_parameter_alignment_on_call
included:
  - Sources/GryphonLib
  - Tests/GryphonLibTests
excluded:
  - Examples
  - Sources/GryphonLib/CwlRandom.swift

line_length: 100

trailing_comma:
  mandatory_comma: true
