disabled_rules: # rule identifiers to exclude from running
  - statement_position
  - opening_brace
  # - line_length

  - void_return
  - todo
  - identifier_name
  - type_body_length
  - file_length
  - force_try
  - force_cast
  - large_tuple
  - cyclomatic_complexity
  - function_body_length
  - trailing_comma
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Sources/GryphonLib
  - Tests/GryphonLibTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Sources/GryphonLib/CwlRandom.swift
  - Examples

line_length: 100
