./.build/debug/Gryphon \
	-emit-kotlin \
	-output-file-map=output-file-map.json \
	-indentation=4 \
	-q \
	Sources/GryphonLib/SwiftStandardLibrary.swift \
	Sources/GryphonLib/PrintableAsTree.swift \
	Sources/GryphonLib/SwiftAST.swift \
	Sources/GryphonLib/SwiftTranslator.swift \
	Sources/GryphonLib/GryphonAST.swift \
	Sources/GryphonLib/TranslationResult.swift \
	Sources/GryphonLib/TranspilationContext.swift \
	Sources/GryphonLib/TranspilationPass.swift \
	Sources/GryphonLib/ASTDumpDecoder.swift \
	Sources/GryphonLib/AuxiliaryFileContents.swift \
	Sources/GryphonLib/Compiler.swift \
	Sources/GryphonLib/SourceFile.swift \
	Sources/GryphonLib/Driver.swift \
	Sources/GryphonLib/Extensions.swift \
	Sources/GryphonLib/SharedUtilities.swift \
	Sources/GryphonLib/KotlinTranslator.swift \
	Sources/GryphonLib/LibraryTranspilationPass.swift
